pub mod agent;
pub mod ai;
pub mod approval_gate;
pub mod blackarch;
pub mod capability_layer;
pub mod correlation;
pub mod engine;
pub mod factory;
pub mod filter;
pub mod lock_free_sink;
pub mod mcp;
pub mod middleware;
pub mod native_scanner;
pub mod notifications;
pub mod orchestrator;
pub mod persistence;
pub mod pipeline;
pub mod plugin_loader;
pub mod policy;
pub mod reactive_engine;
pub mod resource_manager;
pub mod sandbox;
pub mod selection;
pub mod sink;
pub mod skills;
pub mod source_analyzer;
pub mod temporal;
pub mod validation;
pub mod verification;
pub mod waf;
pub mod web;

#[cfg(test)]
pub mod tests;

pub use correlation::{AttackGraph, AttackPath, CorrelationEngine};
pub use filter::FalsePositiveFilter;
pub use orchestrator::Orchestrator;
pub use pipeline::{Pipeline, PipelineBuilder};
pub use sink::{DataSink, JsonlSink, PostgresSink};
pub use validation::PocValidator;
